# Generated by Django 5.0.3 on 2024-03-10 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_task_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_task_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
