name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DB_NAME: ':memory:'
      DB_USER: ''
      DB_PASSWORD: ''
      DB_HOST: ''
      DB_PORT: ''
      DEBUG: 'False'

    strategy:
      matrix:
        python-version: [3.10.x, 3.11, 3.12]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Configure Django for SQLite
        run: |
          sed -i "s/'ENGINE': 'django.db.backends.postgresql'/'ENGINE': 'django.db.backends.sqlite3'/g" gestionnaire_taches_project/settings.py
          sed -i "s/'NAME': os.getenv('DB_NAME')/'NAME': ':memory:'/g" gestionnaire_taches_project/settings.py
        shell: /usr/bin/bash -e {0}
      - name: Run migrations
        run: python manage.py migrate
      - name: Run tests
        run: python manage.py test
